version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - "< 4.2.3, >= 4.2.2.a"
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - "< 4.2, > 4.1.5"
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - "< 4.2.6, >= 4.2.5.a"
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - "< 4.4, >= 4.3.a"
  - dependency-name: io.github.classgraph:classgraph
    versions:
    - "< 4.5, >= 4.4.a"
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
