language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install: true
script: "./mvnw clean install"
after_success:
- "./travis-ci/travis-coveralls-report.sh"
- "./travis-ci/travis-deploy.sh"
env:
  global:
  - secure: Aq+1PsvZoRPi4/yvKfF9b7PFPb6BGwjBKwva3nJznT7yDO7H2QjpZEs8csvnobdNf5zCdSJGifcxhQjKpwD1YF5Y3Szw9bSFBE0UsNmuJY0Ls92fqSwEJmfs81gEs2VLgdXTP1jt4t2hzjyY77C1t3wQYjLebZ25tza2N6cl8xQDL9uq35kdgfE3oy/Alws7Kgf2rO7N5BibKTIau0a4qcRJIIOK/2/8hhCt/9ER9SgDwwmNeicfDQ9afau90ONqoKszhIiiOY3m2ml8UiZTCATTYr8FsiEd704sMWiWiwXoH1gCII8YZAvBv7gh2ZY6PC/BOaaqXpA3BULOFX2ROtauLFnFJANXUL7lHaclzXMjf/hLQBWgFeYomud1f7zaN4uS2ow+PdgMGeeh8qAv9Iri5u6+hS3sm4XPyIkFK9mlnLLVMDEtZkZZf4+YzyUp0Fxk02ShfBdjTvfWo7A1+RFuR+gy5lIYpqhof1AHEKiINFvs7mgmQarvNVbm+qT19vHwhvE5umovWw+k1vykO3/ulzE6u36aeNGpqCzEXmDRbxzmigDsQA0hMuiiaLcS7uh2YrSkG8N96Pd07U0DqiaCrTB7zqaBmCfMlLtdd2pJMyQXLksyxaGbxTcgC13s2ROUfuOzk40sA0nByILveht+NqrCxlYcwitWi/8ITZU=
  - secure: fyBNtzMfKiERJWfvfSPr6jk/TKwHIM3H7EAjtr2SY18cyLz/oHVxp99x2pOkyZz5RVtMapmbKIil0eXP3+Ws2YqOTYHNPBCLNVSmkgBzB4NLiOYWE91OytFVDxeotRT++NvEkWXSjnFtfhpBw1UEfWyP/lkdA+qeOQwfh66mUydQ1Ic3xt/88GGvZwhuNk5fWW0UmlIQY5g7QnLZKf24w4vkkhhswDieNPUvNDjpv1ZamvTYYB8dhtzWmwOY6pTrEOXlFg7g8pgFA5IQHSeFSPKZEMdERkffeN5acXDA6cUsinzuwHcJ7ASlmbw2jWLwwyZFIDI+qDpJ1qK9XBg9eHNMiDlM9FMeEsHOy2CeFytnvVcJEhFlqdWeH8lIa1jNO8p4+5njJI1/kIjVXIzihuljYgenbGxhPZ+gyD1YtmFdu2zt3MLIhysdc92CCR+W46QPLWpI2tufaPm7lQ65/hLReNF6uS+EAi9d45kfczizDpCOn+oqxEYe5zLsZB0Di3zj3cEHxBqq46ROKuLCeXGnREro5H2YTz+HPOI7KVyYF+nvlEproGfcLImH9sxCQFaYXAU5Bv5fgOFa1qmMN3Ku+oMsmuo6LIJPclxcRjT7iy1Qxokgqe9A+fQEMhM24URndxjd8nu444taSm5/xxxF04gxM/Zk07/WXxNfuGo=
