name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only needs to be able to run builder module, other outputs are xml
        # latest-lts
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v3.2.0
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: build-jar
        run: mvn -B install
