name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16, 17-ea ]
    steps:
      - uses: actions/checkout@v2
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: build-jar
        run: mvn -B install
